# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-24 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleResponseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_id', models.CharField(max_length=50)),
                ('mid', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=150)),
                ('to_mid', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '评论回复',
                'db_table': 'Enterprise_response',
            },
        ),
        migrations.CreateModel(
            name='AutomateMessagePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(blank=True, db_column='Industry', max_length=255, null=True)),
                ('province', models.CharField(blank=True, db_column='Province', max_length=255, null=True)),
                ('business_scope', models.CharField(blank=True, db_column='Business_scope', max_length=255, null=True)),
                ('filter', models.CharField(blank=True, db_column='Filter', max_length=255, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('trade_name', models.CharField(blank=True, db_column='Trade_name', max_length=255, null=True)),
                ('sending_time_setting', models.CharField(blank=True, db_column='Sending_time_setting', max_length=255, null=True)),
                ('amount', models.CharField(blank=True, db_column='Amount', max_length=255, null=True)),
                ('task_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Automate_message_post',
            },
        ),
        migrations.CreateModel(
            name='AutomateMessageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, db_column='Amount', max_length=255, null=True)),
                ('task_id', models.CharField(blank=True, db_column='Task_id', max_length=255, null=True)),
                ('success', models.CharField(blank=True, db_column='Success', max_length=255, null=True)),
                ('unknow', models.CharField(blank=True, db_column='Unknow', max_length=255, null=True)),
                ('failed', models.CharField(blank=True, db_column='Failed', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Automate_message_status',
            },
        ),
        migrations.CreateModel(
            name='CommentsOnArticlesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise', models.CharField(max_length=50)),
                ('thumbs_up', models.SmallIntegerField(default=0)),
                ('content', models.CharField(max_length=150)),
                ('is_examine', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '评论',
                'db_table': 'Enterprise_comment',
            },
        ),
        migrations.CreateModel(
            name='CustomerLogin',
            fields=[
                ('customer_id', models.AutoField(db_column='Customer_id', primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=20, null=True)),
                ('identity_status', models.CharField(blank=True, db_column='Identity_status', max_length=255, null=True)),
                ('administrator_status', models.CharField(blank=True, db_column='Administrator_status', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Customer_login',
            },
        ),
        migrations.CreateModel(
            name='EnterpriseArticlesChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='频道名称')),
                ('sequence', models.SmallIntegerField(verbose_name='组内顺序')),
            ],
        ),
        migrations.CreateModel(
            name='EnterpriseArticlesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(blank=True, max_length=250, null=True)),
                ('content', models.CharField(max_length=3000)),
                ('enterprise', models.CharField(max_length=30)),
                ('thumbs_up', models.SmallIntegerField(default=0)),
                ('is_examine', models.BooleanField(default=False)),
                ('is_recommend', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThumbsUpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbs_up_type', models.SmallIntegerField(verbose_name='点赞类型')),
                ('cover_mid', models.IntegerField()),
                ('up_mid', models.IntegerField()),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '点赞记录',
                'db_table': 'Enterprise_Thumbs_Up',
            },
        ),
    ]
