# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-24 14:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisearticlesmodel',
            name='author',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enterprisearticlesmodel',
            name='enterprise_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Contact.EnterpriseArticlesChannel'),
        ),
        migrations.AddField(
            model_name='commentsonarticlesmodel',
            name='mid',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='automatemessagestatus',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='Customer_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Contact.CustomerLogin'),
        ),
        migrations.AddField(
            model_name='automatemessagepost',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='Customer_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Contact.CustomerLogin'),
        ),
        migrations.AddField(
            model_name='articleresponsemodel',
            name='comment',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='Contact.CommentsOnArticlesModel'),
        ),
    ]
