# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-24 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACount',
            fields=[
                ('access_count', models.IntegerField(blank=True, null=True)),
                ('recommended_count', models.IntegerField(blank=True, null=True)),
                ('company_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'A_count',
            },
        ),
        migrations.CreateModel(
            name='BCount',
            fields=[
                ('access_count', models.IntegerField(blank=True, null=True)),
                ('recommended_count', models.IntegerField(blank=True, null=True)),
                ('company_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'B_count',
            },
        ),
        migrations.CreateModel(
            name='CCount',
            fields=[
                ('access_count', models.IntegerField(blank=True, null=True)),
                ('recommended_count', models.IntegerField(blank=True, null=True)),
                ('company_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'C_count',
            },
        ),
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=28, verbose_name='行业')),
                ('eng_industry', models.CharField(max_length=20, verbose_name='行业英文名')),
            ],
            options={
                'verbose_name': '行业信息',
                'db_table': 'db_Chain',
            },
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=16, verbose_name='总数')),
            ],
            options={
                'verbose_name': '行业信息',
                'db_table': 'db_Count',
            },
        ),
        migrations.CreateModel(
            name='Datasummary',
            fields=[
                ('summary_id', models.AutoField(db_column='Summary_id', primary_key=True, serialize=False)),
                ('industry', models.CharField(blank=True, db_column='Industry', max_length=255, null=True)),
                ('province', models.CharField(blank=True, db_column='Province', max_length=255, null=True)),
                ('amount', models.IntegerField(blank=True, db_column='Amount', null=True)),
            ],
            options={
                'db_table': 'datasummary',
            },
        ),
        migrations.CreateModel(
            name='DatasummaryForUp',
            fields=[
                ('summary_id', models.AutoField(db_column='Summary_id', primary_key=True, serialize=False)),
                ('industry', models.CharField(blank=True, db_column='Industry', max_length=255, null=True)),
                ('province', models.CharField(blank=True, db_column='Province', max_length=255, null=True)),
                ('amount', models.IntegerField(blank=True, db_column='Amount', null=True)),
                ('industryid', models.IntegerField(verbose_name='行业id')),
            ],
            options={
                'db_table': 'datasummary_for_up',
            },
        ),
        migrations.CreateModel(
            name='DCount',
            fields=[
                ('access_count', models.IntegerField(blank=True, null=True)),
                ('recommended_count', models.IntegerField(blank=True, null=True)),
                ('company_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'D_count',
            },
        ),
        migrations.CreateModel(
            name='ECount',
            fields=[
                ('access_count', models.IntegerField(blank=True, null=True)),
                ('recommended_count', models.IntegerField(blank=True, null=True)),
                ('company_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'E_count',
            },
        ),
        migrations.CreateModel(
            name='EnterpriseInformationForCustomer',
            fields=[
                ('company_id_customized', models.AutoField(db_column='Company_id_customized', primary_key=True, serialize=False)),
                ('unified_social_credit_code', models.CharField(blank=True, db_column='Unified_social_credit_code', max_length=50, null=True)),
                ('column_registered_capital', models.CharField(blank=True, db_column='Column_registered_capital', max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('legal_representative', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_authority', models.CharField(blank=True, max_length=255, null=True)),
                ('established_time', models.DateTimeField(blank=True, null=True)),
                ('type_of_enterprise', models.CharField(blank=True, max_length=50, null=True)),
                ('industry_involved', models.CharField(blank=True, max_length=50, null=True)),
                ('staff_size', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('mailbox', models.CharField(blank=True, max_length=100, null=True)),
                ('official_website', models.CharField(blank=True, max_length=2000, null=True)),
                ('business_address', models.CharField(blank=True, db_column='Business_address', max_length=255, null=True)),
                ('business_scope', models.TextField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_mark', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(blank=True, db_column='Province', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Enterprise_information_for_customer',
            },
        ),
        migrations.CreateModel(
            name='Enterprises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise', models.CharField(max_length=128, verbose_name='企业')),
                ('access_count', models.IntegerField(default=1, verbose_name='访问数量')),
                ('recommended_count', models.IntegerField(default=1, verbose_name='推荐总数')),
            ],
            options={
                'db_table': 'db_Enterprises',
            },
        ),
        migrations.CreateModel(
            name='FCount',
            fields=[
                ('access_count', models.IntegerField(blank=True, null=True)),
                ('recommended_count', models.IntegerField(blank=True, null=True)),
                ('company_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'F_count',
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_page', models.BooleanField(default=0, verbose_name='默认首页状态')),
                ('i_recommend', models.BooleanField(default=0, verbose_name='我推荐状态')),
                ('company_id', models.CharField(max_length=50, verbose_name='企业id')),
                ('industry_id', models.CharField(max_length=50, verbose_name='行业id')),
                ('follow', models.CharField(max_length=5, null=True, verbose_name='临时关注字段')),
            ],
            options={
                'verbose_name': '企业基本信息',
                'db_table': 'db_Function',
            },
        ),
        migrations.CreateModel(
            name='GCount',
            fields=[
                ('access_count', models.IntegerField(blank=True, null=True)),
                ('recommended_count', models.IntegerField(blank=True, null=True)),
                ('company_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'G_count',
            },
        ),
        migrations.CreateModel(
            name='HCount',
            fields=[
                ('access_count', models.IntegerField(blank=True, null=True)),
                ('recommended_count', models.IntegerField(blank=True, null=True)),
                ('company_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'H_count',
            },
        ),
        migrations.CreateModel(
            name='ICount',
            fields=[
                ('access_count', models.IntegerField(blank=True, null=True)),
                ('recommended_count', models.IntegerField(blank=True, null=True)),
                ('company_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'I_count',
            },
        ),
        migrations.CreateModel(
            name='JCount',
            fields=[
                ('access_count', models.IntegerField(blank=True, null=True)),
                ('recommended_count', models.IntegerField(blank=True, null=True)),
                ('company_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'J_count',
            },
        ),
        migrations.CreateModel(
            name='KCount',
            fields=[
                ('access_count', models.IntegerField(blank=True, null=True)),
                ('recommended_count', models.IntegerField(blank=True, null=True)),
                ('company_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'K_count',
            },
        ),
        migrations.CreateModel(
            name='LCount',
            fields=[
                ('access_count', models.IntegerField(blank=True, null=True)),
                ('recommended_count', models.IntegerField(blank=True, null=True)),
                ('company_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'L_count',
            },
        ),
        migrations.CreateModel(
            name='MCount',
            fields=[
                ('access_count', models.IntegerField(blank=True, null=True)),
                ('recommended_count', models.IntegerField(blank=True, null=True)),
                ('company_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'M_count',
            },
        ),
        migrations.CreateModel(
            name='NCount',
            fields=[
                ('access_count', models.IntegerField(blank=True, null=True)),
                ('recommended_count', models.IntegerField(blank=True, null=True)),
                ('company_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'N_count',
            },
        ),
        migrations.CreateModel(
            name='OCount',
            fields=[
                ('access_count', models.IntegerField(blank=True, null=True)),
                ('recommended_count', models.IntegerField(blank=True, null=True)),
                ('company_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'O_count',
            },
        ),
        migrations.CreateModel(
            name='PCount',
            fields=[
                ('access_count', models.IntegerField(blank=True, null=True)),
                ('recommended_count', models.IntegerField(blank=True, null=True)),
                ('company_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'P_count',
            },
        ),
        migrations.CreateModel(
            name='PreciseRetrieval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=30, verbose_name='行业')),
                ('provinces', models.CharField(max_length=30, verbose_name='省份')),
                ('business', models.CharField(max_length=30, verbose_name='业务')),
                ('enterprise', models.CharField(max_length=30, verbose_name='企业名称')),
                ('certification', models.BooleanField(default=False, verbose_name='企业认证')),
                ('money', models.BigIntegerField(verbose_name='注册资金')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
            ],
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinces', models.CharField(max_length=20, verbose_name='省份')),
            ],
            options={
                'verbose_name': '省份信息',
                'db_table': 'db_Provinces',
            },
        ),
        migrations.CreateModel(
            name='QCount',
            fields=[
                ('access_count', models.IntegerField(blank=True, null=True)),
                ('recommended_count', models.IntegerField(blank=True, null=True)),
                ('company_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Q_count',
            },
        ),
        migrations.CreateModel(
            name='RCount',
            fields=[
                ('access_count', models.IntegerField(blank=True, null=True)),
                ('recommended_count', models.IntegerField(blank=True, null=True)),
                ('company_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'R_count',
            },
        ),
        migrations.CreateModel(
            name='SCount',
            fields=[
                ('access_count', models.IntegerField(blank=True, null=True)),
                ('recommended_count', models.IntegerField(blank=True, null=True)),
                ('company_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'S_count',
            },
        ),
        migrations.CreateModel(
            name='TCount',
            fields=[
                ('access_count', models.IntegerField(blank=True, null=True)),
                ('recommended_count', models.IntegerField(blank=True, null=True)),
                ('company_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'T_count',
            },
        ),
    ]
