# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-24 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Enterprise', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Users.EnterpriseCertificationInfo', verbose_name='外键'),
        ),
        migrations.AddField(
            model_name='enterprises',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enterprise.Chain', verbose_name='外键'),
        ),
        migrations.AddField(
            model_name='enterprises',
            name='provinces',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enterprise.Provinces', verbose_name='外键'),
        ),
        migrations.AddField(
            model_name='enterpriseinformationforcustomer',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Enterprise.Enterprises', verbose_name='外键'),
        ),
        migrations.AddField(
            model_name='count',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enterprise.Chain', verbose_name='外键'),
        ),
        migrations.AddField(
            model_name='count',
            name='provinces',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enterprise.Provinces', verbose_name='外键'),
        ),
    ]
