# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-20 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wxorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('wechat', models.CharField(max_length=32, verbose_name='微信号')),
                ('body', models.CharField(max_length=256, verbose_name='商品描述')),
                ('out_trade_no', models.CharField(max_length=64, unique=True, verbose_name='订单号')),
                ('transaction_id', models.CharField(default='', max_length=64, verbose_name='微信支付订单号')),
                ('total_fee', models.BigIntegerField(verbose_name='订单的资金总额,单位为分')),
                ('product_id', models.CharField(max_length=16, verbose_name='商品ID')),
                ('notify_url', models.CharField(max_length=500, verbose_name='支付完成通知url')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
            ],
            options={
                'verbose_name': '微信订单',
                'verbose_name_plural': '微信订单',
            },
        ),
        migrations.CreateModel(
            name='Wxpay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('out_trade_no', models.CharField(blank=True, max_length=64, null=True, verbose_name='订单号')),
                ('pay_no', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='支付唯一订单号')),
                ('code_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='二维码地址')),
                ('nonce_str', models.CharField(blank=True, max_length=32, null=True, verbose_name='随机字符串')),
            ],
            options={
                'verbose_name': '微信支付',
                'verbose_name_plural': '微信支付',
            },
        ),
    ]
