# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-24 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('Title', models.CharField(blank=True, db_column='Title', max_length=300, null=True)),
                ('BidsPirce', models.CharField(blank=True, db_column='BidsPrice', max_length=50, null=True)),
                ('Company', models.CharField(blank=True, db_column='Company', max_length=200, null=True)),
                ('Url', models.CharField(blank=True, db_column='Url', max_length=200, null=True)),
                ('Source', models.CharField(blank=True, db_column='Source', max_length=200, null=True)),
                ('ReleaseDate', models.CharField(blank=True, db_column='ReleaseDate', max_length=50, null=True)),
                ('StartDate', models.CharField(blank=True, db_column='StartDate', max_length=50, null=True)),
                ('EndDate', models.DateField(blank=True, db_column='EndDate', null=True)),
                ('BidsAreaID', models.CharField(blank=True, db_column='BidsAreaID', max_length=50, null=True)),
                ('IsValid', models.IntegerField(blank=True, db_column='IsValid', null=True)),
                ('IsDeleted', models.IntegerField(blank=True, db_column='IsDeleted', null=True)),
                ('CreateTime', models.DateField(auto_now_add=True, db_column='CreateTime')),
                ('BidsContent', models.TextField(blank=True, db_column='BidsContent', null=True)),
                ('Phone', models.CharField(blank=True, db_column='Phone', max_length=100, null=True)),
            ],
            options={
                'verbose_name': '文章表',
                'verbose_name_plural': '文章表',
                'db_table': 'web_bids',
            },
        ),
        migrations.CreateModel(
            name='BidsUserSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areas_id', models.CharField(max_length=60, verbose_name='关注省范围')),
                ('keywords_array', models.CharField(max_length=60, verbose_name='关注关键字')),
                ('remind_long_time', models.SmallIntegerField(default=7, verbose_name='推送时常')),
                ('is_remind', models.BooleanField(default=True, verbose_name='是否推送')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '推送用户记录表',
                'verbose_name_plural': '推送用户记录表',
                'db_table': 'Subscribe_status',
            },
        ),
    ]
