# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-24 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单批总金额')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='余额')),
            ],
            options={
                'db_table': 'db_ConsumptionRecord',
            },
        ),
        migrations.CreateModel(
            name='EnterpriseCertificationInfo',
            fields=[
                ('company_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='企业id')),
                ('name', models.CharField(max_length=50, verbose_name='企业名字')),
                ('code', models.CharField(max_length=50, verbose_name='信用代码')),
                ('avatar', models.CharField(max_length=200, verbose_name='营业执照')),
                ('contacts', models.CharField(max_length=20, verbose_name='联系人')),
                ('phone', models.CharField(max_length=50, verbose_name='电话号码')),
                ('identity_status', models.SmallIntegerField(choices=[(1, '待审核'), (2, '审核通过'), (3, '不通过')], default=1, verbose_name='审核状态')),
                ('industryid', models.CharField(max_length=5, null=True, verbose_name='行业id')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('administrator_status', models.CharField(max_length=10, null=True, verbose_name='管理员状态')),
                ('reviewer_time', models.DateField(null=True, verbose_name='审核通过时间')),
                ('reviewer_name', models.CharField(max_length=50, null=True, verbose_name='审核人')),
                ('opinion', models.CharField(max_length=100, null=True, verbose_name='审核意见')),
                ('province', models.CharField(max_length=20, null=True, verbose_name='省份')),
                ('industry', models.CharField(max_length=100, null=True, verbose_name='行业')),
                ('demand_config', models.CharField(default='1', max_length=120, verbose_name='配置需求')),
            ],
            options={
                'db_table': 'db_EnterpriseCertificationInfo',
            },
        ),
        migrations.CreateModel(
            name='ManualMessagePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(blank=True, db_column='Customer_id', null=True)),
                ('industry', models.CharField(blank=True, db_column='Industry', max_length=255, null=True)),
                ('province', models.CharField(blank=True, db_column='Province', max_length=255, null=True)),
                ('business_scope', models.CharField(blank=True, db_column='Business_scope', max_length=255, null=True)),
                ('filter', models.CharField(blank=True, db_column='Filter', max_length=255, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('task_id', models.CharField(blank=True, db_column='Task_id', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Manual_message_post',
            },
        ),
        migrations.CreateModel(
            name='ManualMessageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(blank=True, db_column='Customer_id', null=True)),
                ('amount', models.CharField(blank=True, db_column='Amount', max_length=255, null=True)),
                ('task_id', models.CharField(blank=True, db_column='Task_id', max_length=255, null=True)),
                ('success', models.CharField(blank=True, db_column='Success', max_length=255, null=True)),
                ('unknow', models.CharField(blank=True, db_column='Unknow', max_length=255, null=True)),
                ('failed', models.CharField(blank=True, db_column='Failed', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Manual_message_status',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('company_id', models.CharField(max_length=100, verbose_name='企业id')),
                ('order_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='订单号')),
                ('total_count', models.IntegerField(default=1, verbose_name='号码总数')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单批总金额')),
                ('sms_type', models.CharField(max_length=50, verbose_name='发送类型')),
                ('username', models.CharField(max_length=50, verbose_name='用户')),
                ('mobile', models.CharField(max_length=2000, verbose_name='手机号')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
            ],
            options={
                'db_table': 'db_Order',
            },
        ),
        migrations.CreateModel(
            name='PayCertificationInfo',
            fields=[
                ('order_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='订单id')),
                ('user_id', models.CharField(max_length=15, verbose_name='用户')),
                ('openid', models.CharField(max_length=80, verbose_name='打开id')),
                ('money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('company_name', models.CharField(max_length=100, verbose_name='企业名称')),
                ('mobile', models.CharField(max_length=20, verbose_name='联系人电话')),
                ('name', models.CharField(max_length=20, verbose_name='联系人')),
            ],
            options={
                'db_table': 'db_PayCertificationInfo',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_count', models.IntegerField(verbose_name='手机号的总数')),
                ('send_count', models.IntegerField(verbose_name='发送短信的总数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.EnterpriseCertificationInfo')),
            ],
            options={
                'verbose_name': '记录表',
                'db_table': 'db_Record',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=50, verbose_name='模板名称')),
                ('sms_type', models.CharField(max_length=50, verbose_name='发送类型')),
                ('data_time', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('user', models.CharField(max_length=50, verbose_name='操作用户')),
                ('content', models.CharField(max_length=500, verbose_name='发送内容')),
                ('reviewer_time', models.DateField(null=True, verbose_name='审核通过时间')),
                ('reviewer_name', models.CharField(max_length=50, null=True, verbose_name='审核人')),
                ('state', models.SmallIntegerField(choices=[(1, '待审核'), (2, '审核通过'), (3, '不通过')], default=1, verbose_name='审核状态')),
            ],
            options={
                'db_table': 'db_Template',
            },
        ),
        migrations.CreateModel(
            name='Top_up_Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总金额')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.EnterpriseCertificationInfo')),
            ],
            options={
                'verbose_name': '充值表',
                'db_table': 'db_Top_up_Payment',
            },
        ),
    ]
