# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-24 05:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisecertificationinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
        migrations.AddField(
            model_name='consumptionrecord',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Users.EnterpriseCertificationInfo', verbose_name='消费企业'),
        ),
        migrations.AddField(
            model_name='consumptionrecord',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Users.Order', verbose_name='订单号'),
        ),
    ]
