# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-24 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20190624_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisecertificationinfo',
            name='username',
            field=models.CharField(max_length=100, null=True, verbose_name='用户名'),
        ),
    ]
