# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-15 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_remove_area_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='isDeleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
