# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-14 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('pirce', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('company', models.CharField(max_length=100, verbose_name='公司')),
                ('url', models.CharField(max_length=200, verbose_name='地址')),
                ('source', models.CharField(max_length=100, verbose_name='来源')),
                ('isValid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('isDeleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('areas_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='province_addresses', to='areas.Area', verbose_name='地区')),
            ],
            options={
                'verbose_name_plural': '文章表',
                'verbose_name': '文章表',
                'db_table': 'up_bids',
            },
        ),
    ]
