# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-21 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('pirce', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('company', models.CharField(max_length=100, verbose_name='公司')),
                ('url', models.CharField(max_length=200, verbose_name='地址')),
                ('source', models.CharField(max_length=100, verbose_name='来源')),
                ('content', models.TextField(blank=True, default=None, null=True, verbose_name='文章内容')),
                ('isValid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('isDeleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('by_time', models.DateField(auto_now_add=True, null=True, verbose_name='截止时间')),
                ('areas_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='province_addresses', to='areas.Area', verbose_name='地区')),
            ],
            options={
                'verbose_name': '文章表',
                'db_table': 'up_bids',
                'verbose_name_plural': '文章表',
            },
        ),
        migrations.CreateModel(
            name='BidsUserSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('areas_id', models.CharField(max_length=60, verbose_name='关注省范围')),
                ('keywords_array', models.CharField(max_length=60, verbose_name='关注关键字')),
                ('remind_long_time', models.SmallIntegerField(default=7, verbose_name='推送时常')),
                ('is_remind', models.BooleanField(default=True, verbose_name='是否推送')),
            ],
            options={
                'verbose_name': '推送用户记录表',
                'db_table': 'up_user_bids_setting',
                'verbose_name_plural': '推送用户记录表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='用户名')),
                ('image_url', models.CharField(max_length=200, null=True, verbose_name='t头像图片')),
                ('article', models.ManyToManyField(related_name='collections', to='subscribe.Bids')),
                ('bids_set_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='bidset', to='subscribe.BidsUserSetting', verbose_name='订阅表')),
            ],
            options={
                'verbose_name': '用户表',
                'db_table': 'up_user',
                'verbose_name_plural': '用户表',
            },
        ),
    ]
