# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-14 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidsUserSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('areas_id', models.CharField(max_length=60, verbose_name='关注省范围')),
                ('keywords_array', models.CharField(max_length=50, verbose_name='关注关键字')),
                ('remind_time', models.TimeField(verbose_name='推送时间')),
                ('is_remind', models.BooleanField(default=True, verbose_name='是否推送')),
            ],
            options={
                'verbose_name_plural': '推送用户记录表',
                'verbose_name': '推送用户记录表',
                'db_table': 'up_user_bids_setting',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neme', models.CharField(max_length=30, null=True, verbose_name='用户名')),
            ],
            options={
                'verbose_name_plural': '用户表',
                'verbose_name': '用户表',
                'db_table': 'up_user',
            },
        ),
        migrations.AddField(
            model_name='bidsusersetting',
            name='mid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='subscribe.User', verbose_name='用户'),
        ),
    ]
