# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-21 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bids_set_id',
        ),
        migrations.AddField(
            model_name='bidsusersetting',
            name='mid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscribe.User', verbose_name='用户'),
        ),
    ]
