# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-22 05:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_auto_20190521_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='article',
        ),
        migrations.AlterModelTable(
            name='bidsusersetting',
            table='Subscribe_status',
        ),
    ]
