# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-14 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_auto_20190514_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidsusersetting',
            name='remind_long_time',
            field=models.SmallIntegerField(choices=[(1, 7), (2, 30), (3, 90)], default=1, verbose_name='推送时常'),
        ),
    ]
