# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-15 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0004_auto_20190515_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidsContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('bids_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscribe.Bids', verbose_name='文章')),
            ],
            options={
                'verbose_name_plural': '文章内容',
                'verbose_name': '文章内容',
                'db_table': 'up_bids_content',
            },
        ),
        migrations.CreateModel(
            name='BidsUserRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='bidsusersetting',
            name='remind_time',
        ),
    ]
