# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-15 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0005_auto_20190515_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bids_set_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='bidset', to='subscribe.BidsUserSetting', verbose_name='订阅表'),
        ),
    ]
