# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-15 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0006_auto_20190515_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidscontent',
            name='bids_id',
        ),
        migrations.AddField(
            model_name='bids',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='文章内容'),
        ),
        migrations.DeleteModel(
            name='BidsContent',
        ),
    ]
