# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-15 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0007_auto_20190515_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='content',
            field=models.CharField(blank=True, default=None, max_length=4000, null=True, verbose_name='文章内容'),
        ),
    ]
