# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-16 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0010_auto_20190516_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='areas_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='province_addresses', to='areas.Area', verbose_name='地区'),
        ),
    ]
