# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-16 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0012_auto_20190516_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='content',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='文章内容'),
        ),
    ]
