# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-16 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0013_auto_20190516_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='create_time',
            field=models.DateField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='bidsusersetting',
            name='create_time',
            field=models.DateField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
