# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-16 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0016_articledetailmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledetailmodel',
            name='bids_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bidset', to='subscribe.Bids', verbose_name='订阅表'),
        ),
    ]
