# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-17 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0017_articledetailmodel_bids_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BidsUserRecord',
        ),
        migrations.AddField(
            model_name='articledetailmodel',
            name='focus',
            field=models.BooleanField(default=False, verbose_name='是否关注'),
        ),
        migrations.AddField(
            model_name='bidsusersetting',
            name='by_time',
            field=models.TimeField(null=True, verbose_name='截止时间'),
        ),
    ]
