# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-18 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0019_auto_20190517_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='article',
            field=models.ManyToManyField(related_name='collection', to='subscribe.Bids'),
        ),
    ]
