# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-18 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0020_auto_20190518_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='article',
            field=models.ManyToManyField(related_name='collections', to='subscribe.Bids'),
        ),
    ]
