# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-18 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0021_auto_20190518_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='by_time',
            field=models.TimeField(null=True, verbose_name='截止时间'),
        ),
    ]
