# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-20 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0022_bids_by_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='by_time',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='截止时间'),
        ),
    ]
