# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-24 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus', models.BooleanField(default=False, verbose_name='是否关注')),
            ],
            options={
                'verbose_name': '中间表',
                'db_table': 'db_Associated',
            },
        ),
        migrations.CreateModel(
            name='Grouping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grouping', models.CharField(max_length=128, verbose_name='分组名称')),
            ],
            options={
                'verbose_name': '分组信息表',
                'db_table': 'db_Grouping',
            },
        ),
    ]
