# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-24 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Enterprise', '0001_initial'),
        ('Chainring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='associated',
            name='enterprisesid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enterprise.Enterprises'),
        ),
        migrations.AddField(
            model_name='associated',
            name='groupingid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chainring.Grouping'),
        ),
    ]
