# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-26 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, verbose_name='被访问的url')),
                ('userid', models.CharField(max_length=10, verbose_name='用户id')),
                ('username', models.CharField(max_length=10, verbose_name='用户名字')),
                ('city', models.CharField(max_length=20, null=True, verbose_name='城市')),
                ('province', models.CharField(max_length=20, null=True, verbose_name='省份')),
                ('headimgUrl', models.CharField(max_length=200, null=True, verbose_name='头像url')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '监控后台信息表',
                'db_table': 'db_MonitorsInfo',
            },
        ),
    ]
